permalink: /:title/
version: 1.1  # Change the number each time you update CSS

title: "Connecting the Dots: From Artist to Programmer"
email: "casswillis@tutamail.com"
description: >-
  Cass Willis is a visual artist and wannabe AI programmer, diving headfirst into the world of artificial intelligence, one Python script at a time. This blog is her way of documenting that journey: the struggles, the breakthroughs, and everything in between.

baseurl: ""  # The subpath of your site, e.g., /blog
url: ""  # The base hostname & protocol for your site, e.g., http://example.com
github_username: "casswillis"

# Set a theme 
theme: minima  # Option A: Use a built-in theme

# Force Jekyll to generate `_site`
destination: _site

# Fix permalink issues
permalink: /:year/:month/:day/:title/

collections:
  posts:
    output: true

# Exclude unnecessary files
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
